[package]
name = "decklink-sdk"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Julian Waller <git@julusian.co.uk>"]
edition = "2018"
build="build.rs"

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
bitflags = "1.0"

[build-dependencies]
cmake = "0.1.38"