/* automatically generated by rust-bindgen */

pub const SEVERITY_SUCCESS: u32 = 0;
pub const SEVERITY_ERROR: u32 = 1;
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 29;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const __TIMESIZE: u32 = 64;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub type HRESULT = ::std::os::raw::c_int;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___fsid_t() {
    assert_eq!(
        ::std::mem::size_of::<__fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__fsid_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__fsid_t>())).__val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__fsid_t),
            "::",
            stringify!(__val)
        )
    );
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type BMDDisplayMode = u32;
pub const _BMDDisplayMode_bmdModeNTSC: _BMDDisplayMode = 1853125475;
pub const _BMDDisplayMode_bmdModeNTSC2398: _BMDDisplayMode = 1853108787;
pub const _BMDDisplayMode_bmdModePAL: _BMDDisplayMode = 1885432864;
pub const _BMDDisplayMode_bmdModeNTSCp: _BMDDisplayMode = 1853125488;
pub const _BMDDisplayMode_bmdModePALp: _BMDDisplayMode = 1885432944;
pub const _BMDDisplayMode_bmdModeHD1080p2398: _BMDDisplayMode = 842231923;
pub const _BMDDisplayMode_bmdModeHD1080p24: _BMDDisplayMode = 842297459;
pub const _BMDDisplayMode_bmdModeHD1080p25: _BMDDisplayMode = 1215312437;
pub const _BMDDisplayMode_bmdModeHD1080p2997: _BMDDisplayMode = 1215312441;
pub const _BMDDisplayMode_bmdModeHD1080p30: _BMDDisplayMode = 1215312688;
pub const _BMDDisplayMode_bmdModeHD1080i50: _BMDDisplayMode = 1214854448;
pub const _BMDDisplayMode_bmdModeHD1080i5994: _BMDDisplayMode = 1214854457;
pub const _BMDDisplayMode_bmdModeHD1080i6000: _BMDDisplayMode = 1214854704;
pub const _BMDDisplayMode_bmdModeHD1080p50: _BMDDisplayMode = 1215313200;
pub const _BMDDisplayMode_bmdModeHD1080p5994: _BMDDisplayMode = 1215313209;
pub const _BMDDisplayMode_bmdModeHD1080p6000: _BMDDisplayMode = 1215313456;
pub const _BMDDisplayMode_bmdModeHD720p50: _BMDDisplayMode = 1752184112;
pub const _BMDDisplayMode_bmdModeHD720p5994: _BMDDisplayMode = 1752184121;
pub const _BMDDisplayMode_bmdModeHD720p60: _BMDDisplayMode = 1752184368;
pub const _BMDDisplayMode_bmdMode2k2398: _BMDDisplayMode = 845886003;
pub const _BMDDisplayMode_bmdMode2k24: _BMDDisplayMode = 845886004;
pub const _BMDDisplayMode_bmdMode2k25: _BMDDisplayMode = 845886005;
pub const _BMDDisplayMode_bmdMode2kDCI2398: _BMDDisplayMode = 845427251;
pub const _BMDDisplayMode_bmdMode2kDCI24: _BMDDisplayMode = 845427252;
pub const _BMDDisplayMode_bmdMode2kDCI25: _BMDDisplayMode = 845427253;
pub const _BMDDisplayMode_bmdMode4K2160p2398: _BMDDisplayMode = 879440435;
pub const _BMDDisplayMode_bmdMode4K2160p24: _BMDDisplayMode = 879440436;
pub const _BMDDisplayMode_bmdMode4K2160p25: _BMDDisplayMode = 879440437;
pub const _BMDDisplayMode_bmdMode4K2160p2997: _BMDDisplayMode = 879440441;
pub const _BMDDisplayMode_bmdMode4K2160p30: _BMDDisplayMode = 879440688;
pub const _BMDDisplayMode_bmdMode4K2160p50: _BMDDisplayMode = 879441200;
pub const _BMDDisplayMode_bmdMode4K2160p5994: _BMDDisplayMode = 879441209;
pub const _BMDDisplayMode_bmdMode4K2160p60: _BMDDisplayMode = 879441456;
pub const _BMDDisplayMode_bmdMode4kDCI2398: _BMDDisplayMode = 878981683;
pub const _BMDDisplayMode_bmdMode4kDCI24: _BMDDisplayMode = 878981684;
pub const _BMDDisplayMode_bmdMode4kDCI25: _BMDDisplayMode = 878981685;
pub const _BMDDisplayMode_bmdModeCintelRAW: _BMDDisplayMode = 1920426857;
pub const _BMDDisplayMode_bmdModeCintelCompressedRAW: _BMDDisplayMode = 1920426851;
pub const _BMDDisplayMode_bmdModeUnknown: _BMDDisplayMode = 1769303659;
pub type _BMDDisplayMode = u32;
pub type BMDFieldDominance = u32;
pub const _BMDFieldDominance_bmdUnknownFieldDominance: _BMDFieldDominance = 0;
pub const _BMDFieldDominance_bmdLowerFieldFirst: _BMDFieldDominance = 1819244402;
pub const _BMDFieldDominance_bmdUpperFieldFirst: _BMDFieldDominance = 1970303090;
pub const _BMDFieldDominance_bmdProgressiveFrame: _BMDFieldDominance = 1886547815;
pub const _BMDFieldDominance_bmdProgressiveSegmentedFrame: _BMDFieldDominance = 1886610976;
pub type _BMDFieldDominance = u32;
pub type BMDPixelFormat = u32;
pub const _BMDPixelFormat_bmdFormat8BitYUV: _BMDPixelFormat = 846624121;
pub const _BMDPixelFormat_bmdFormat10BitYUV: _BMDPixelFormat = 1983000880;
pub const _BMDPixelFormat_bmdFormat8BitARGB: _BMDPixelFormat = 32;
pub const _BMDPixelFormat_bmdFormat8BitBGRA: _BMDPixelFormat = 1111970369;
pub const _BMDPixelFormat_bmdFormat10BitRGB: _BMDPixelFormat = 1915892016;
pub const _BMDPixelFormat_bmdFormat12BitRGB: _BMDPixelFormat = 1378955842;
pub const _BMDPixelFormat_bmdFormat12BitRGBLE: _BMDPixelFormat = 1378955852;
pub const _BMDPixelFormat_bmdFormat10BitRGBXLE: _BMDPixelFormat = 1378955372;
pub const _BMDPixelFormat_bmdFormat10BitRGBX: _BMDPixelFormat = 1378955362;
pub const _BMDPixelFormat_bmdFormatH265: _BMDPixelFormat = 1751479857;
pub const _BMDPixelFormat_bmdFormatDNxHR: _BMDPixelFormat = 1096180840;
pub const _BMDPixelFormat_bmdFormat12BitRAWGRBG: _BMDPixelFormat = 1915826800;
pub const _BMDPixelFormat_bmdFormat12BitRAWJPEG: _BMDPixelFormat = 1915827824;
pub type _BMDPixelFormat = u32;
pub type BMDDisplayModeFlags = u32;
pub const _BMDDisplayModeFlags_bmdDisplayModeSupports3D: _BMDDisplayModeFlags = 1;
pub const _BMDDisplayModeFlags_bmdDisplayModeColorspaceRec601: _BMDDisplayModeFlags = 2;
pub const _BMDDisplayModeFlags_bmdDisplayModeColorspaceRec709: _BMDDisplayModeFlags = 4;
pub type _BMDDisplayModeFlags = u32;
pub type BMDVideoOutputFlags = u32;
pub const _BMDVideoOutputFlags_bmdVideoOutputFlagDefault: _BMDVideoOutputFlags = 0;
pub const _BMDVideoOutputFlags_bmdVideoOutputVANC: _BMDVideoOutputFlags = 1;
pub const _BMDVideoOutputFlags_bmdVideoOutputVITC: _BMDVideoOutputFlags = 2;
pub const _BMDVideoOutputFlags_bmdVideoOutputRP188: _BMDVideoOutputFlags = 4;
pub const _BMDVideoOutputFlags_bmdVideoOutputDualStream3D: _BMDVideoOutputFlags = 16;
pub type _BMDVideoOutputFlags = u32;
pub type BMDPacketType = u32;
pub const _BMDPacketType_bmdPacketTypeStreamInterruptedMarker: _BMDPacketType = 1936289396;
pub const _BMDPacketType_bmdPacketTypeStreamData: _BMDPacketType = 1935958388;
pub type _BMDPacketType = u32;
pub type BMDFrameFlags = u32;
pub const _BMDFrameFlags_bmdFrameFlagDefault: _BMDFrameFlags = 0;
pub const _BMDFrameFlags_bmdFrameFlagFlipVertical: _BMDFrameFlags = 1;
pub const _BMDFrameFlags_bmdFrameContainsHDRMetadata: _BMDFrameFlags = 2;
pub const _BMDFrameFlags_bmdFrameContainsCintelMetadata: _BMDFrameFlags = 4;
pub const _BMDFrameFlags_bmdFrameHasNoInputSource: _BMDFrameFlags = -2147483648;
pub type _BMDFrameFlags = i32;
pub type BMDVideoInputFlags = u32;
pub const _BMDVideoInputFlags_bmdVideoInputFlagDefault: _BMDVideoInputFlags = 0;
pub const _BMDVideoInputFlags_bmdVideoInputEnableFormatDetection: _BMDVideoInputFlags = 1;
pub const _BMDVideoInputFlags_bmdVideoInputDualStream3D: _BMDVideoInputFlags = 2;
pub type _BMDVideoInputFlags = u32;
pub type BMDVideoInputFormatChangedEvents = u32;
pub const _BMDVideoInputFormatChangedEvents_bmdVideoInputDisplayModeChanged:
    _BMDVideoInputFormatChangedEvents = 1;
pub const _BMDVideoInputFormatChangedEvents_bmdVideoInputFieldDominanceChanged:
    _BMDVideoInputFormatChangedEvents = 2;
pub const _BMDVideoInputFormatChangedEvents_bmdVideoInputColorspaceChanged:
    _BMDVideoInputFormatChangedEvents = 4;
pub type _BMDVideoInputFormatChangedEvents = u32;
pub type BMDDetectedVideoInputFormatFlags = u32;
pub const _BMDDetectedVideoInputFormatFlags_bmdDetectedVideoInputYCbCr422:
    _BMDDetectedVideoInputFormatFlags = 1;
pub const _BMDDetectedVideoInputFormatFlags_bmdDetectedVideoInputRGB444:
    _BMDDetectedVideoInputFormatFlags = 2;
pub const _BMDDetectedVideoInputFormatFlags_bmdDetectedVideoInputDualStream3D:
    _BMDDetectedVideoInputFormatFlags = 4;
pub type _BMDDetectedVideoInputFormatFlags = u32;
pub type BMDDeckLinkCapturePassthroughMode = u32;
pub const _BMDDeckLinkCapturePassthroughMode_bmdDeckLinkCapturePassthroughModeDisabled:
    _BMDDeckLinkCapturePassthroughMode = 1885628787;
pub const _BMDDeckLinkCapturePassthroughMode_bmdDeckLinkCapturePassthroughModeDirect:
    _BMDDeckLinkCapturePassthroughMode = 1885628786;
pub const _BMDDeckLinkCapturePassthroughMode_bmdDeckLinkCapturePassthroughModeCleanSwitch:
    _BMDDeckLinkCapturePassthroughMode = 1885564014;
pub type _BMDDeckLinkCapturePassthroughMode = u32;
pub type BMDOutputFrameCompletionResult = u32;
pub const _BMDOutputFrameCompletionResult_bmdOutputFrameCompleted: _BMDOutputFrameCompletionResult =
    0;
pub const _BMDOutputFrameCompletionResult_bmdOutputFrameDisplayedLate:
    _BMDOutputFrameCompletionResult = 1;
pub const _BMDOutputFrameCompletionResult_bmdOutputFrameDropped: _BMDOutputFrameCompletionResult =
    2;
pub const _BMDOutputFrameCompletionResult_bmdOutputFrameFlushed: _BMDOutputFrameCompletionResult =
    3;
pub type _BMDOutputFrameCompletionResult = u32;
pub type BMDReferenceStatus = u32;
pub const _BMDReferenceStatus_bmdReferenceNotSupportedByHardware: _BMDReferenceStatus = 1;
pub const _BMDReferenceStatus_bmdReferenceLocked: _BMDReferenceStatus = 2;
pub type _BMDReferenceStatus = u32;
pub type BMDAudioFormat = u32;
pub const _BMDAudioFormat_bmdAudioFormatPCM: _BMDAudioFormat = 1819304813;
pub type _BMDAudioFormat = u32;
pub type BMDAudioSampleRate = u32;
pub const _BMDAudioSampleRate_bmdAudioSampleRate48kHz: _BMDAudioSampleRate = 48000;
pub type _BMDAudioSampleRate = u32;
pub type BMDAudioSampleType = u32;
pub const _BMDAudioSampleType_bmdAudioSampleType16bitInteger: _BMDAudioSampleType = 16;
pub const _BMDAudioSampleType_bmdAudioSampleType32bitInteger: _BMDAudioSampleType = 32;
pub type _BMDAudioSampleType = u32;
pub type BMDAudioOutputStreamType = u32;
pub const _BMDAudioOutputStreamType_bmdAudioOutputStreamContinuous: _BMDAudioOutputStreamType = 0;
pub const _BMDAudioOutputStreamType_bmdAudioOutputStreamContinuousDontResample:
    _BMDAudioOutputStreamType = 1;
pub const _BMDAudioOutputStreamType_bmdAudioOutputStreamTimestamped: _BMDAudioOutputStreamType = 2;
pub type _BMDAudioOutputStreamType = u32;
pub type BMDDisplayModeSupport = u32;
pub const _BMDDisplayModeSupport_bmdDisplayModeNotSupported: _BMDDisplayModeSupport = 0;
pub const _BMDDisplayModeSupport_bmdDisplayModeSupported: _BMDDisplayModeSupport = 1;
pub const _BMDDisplayModeSupport_bmdDisplayModeSupportedWithConversion: _BMDDisplayModeSupport = 2;
pub type _BMDDisplayModeSupport = u32;
pub type BMDTimecodeFormat = u32;
pub const _BMDTimecodeFormat_bmdTimecodeRP188VITC1: _BMDTimecodeFormat = 1919972913;
pub const _BMDTimecodeFormat_bmdTimecodeRP188VITC2: _BMDTimecodeFormat = 1919955250;
pub const _BMDTimecodeFormat_bmdTimecodeRP188LTC: _BMDTimecodeFormat = 1919970420;
pub const _BMDTimecodeFormat_bmdTimecodeRP188Any: _BMDTimecodeFormat = 1919955256;
pub const _BMDTimecodeFormat_bmdTimecodeVITC: _BMDTimecodeFormat = 1986622563;
pub const _BMDTimecodeFormat_bmdTimecodeVITCField2: _BMDTimecodeFormat = 1986622514;
pub const _BMDTimecodeFormat_bmdTimecodeSerial: _BMDTimecodeFormat = 1936028265;
pub type _BMDTimecodeFormat = u32;
pub type BMDAnalogVideoFlags = u32;
pub const _BMDAnalogVideoFlags_bmdAnalogVideoFlagCompositeSetup75: _BMDAnalogVideoFlags = 1;
pub const _BMDAnalogVideoFlags_bmdAnalogVideoFlagComponentBetacamLevels: _BMDAnalogVideoFlags = 2;
pub type _BMDAnalogVideoFlags = u32;
pub type BMDAudioOutputAnalogAESSwitch = u32;
pub const _BMDAudioOutputAnalogAESSwitch_bmdAudioOutputSwitchAESEBU:
    _BMDAudioOutputAnalogAESSwitch = 1634038560;
pub const _BMDAudioOutputAnalogAESSwitch_bmdAudioOutputSwitchAnalog:
    _BMDAudioOutputAnalogAESSwitch = 1634626663;
pub type _BMDAudioOutputAnalogAESSwitch = u32;
pub type BMDVideoOutputConversionMode = u32;
pub const _BMDVideoOutputConversionMode_bmdNoVideoOutputConversion: _BMDVideoOutputConversionMode =
    1852796517;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputLetterboxDownconversion:
    _BMDVideoOutputConversionMode = 1819566712;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputAnamorphicDownconversion:
    _BMDVideoOutputConversionMode = 1634562152;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHD720toHD1080Conversion:
    _BMDVideoOutputConversionMode = 926036067;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareLetterboxDownconversion:
    _BMDVideoOutputConversionMode = 1213688930;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareAnamorphicDownconversion:
    _BMDVideoOutputConversionMode = 1213686125;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareCenterCutDownconversion:
    _BMDVideoOutputConversionMode = 1213686627;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardware720p1080pCrossconversion:
    _BMDVideoOutputConversionMode = 2019778928;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareAnamorphic720pUpconversion:
    _BMDVideoOutputConversionMode = 1969305456;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareAnamorphic1080iUpconversion:
    _BMDVideoOutputConversionMode = 1969303913;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareAnamorphic149To720pUpconversion:
    _BMDVideoOutputConversionMode = 1966356336;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwareAnamorphic149To1080iUpconversion:
    _BMDVideoOutputConversionMode = 1966354793;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwarePillarbox720pUpconversion:
    _BMDVideoOutputConversionMode = 1970288496;
pub const _BMDVideoOutputConversionMode_bmdVideoOutputHardwarePillarbox1080iUpconversion:
    _BMDVideoOutputConversionMode = 1970286953;
pub type _BMDVideoOutputConversionMode = u32;
pub type BMDVideoInputConversionMode = u32;
pub const _BMDVideoInputConversionMode_bmdNoVideoInputConversion: _BMDVideoInputConversionMode =
    1852796517;
pub const _BMDVideoInputConversionMode_bmdVideoInputLetterboxDownconversionFromHD1080:
    _BMDVideoInputConversionMode = 825257058;
pub const _BMDVideoInputConversionMode_bmdVideoInputAnamorphicDownconversionFromHD1080:
    _BMDVideoInputConversionMode = 825254253;
pub const _BMDVideoInputConversionMode_bmdVideoInputLetterboxDownconversionFromHD720:
    _BMDVideoInputConversionMode = 926051426;
pub const _BMDVideoInputConversionMode_bmdVideoInputAnamorphicDownconversionFromHD720:
    _BMDVideoInputConversionMode = 926048621;
pub const _BMDVideoInputConversionMode_bmdVideoInputLetterboxUpconversion:
    _BMDVideoInputConversionMode = 1818391920;
pub const _BMDVideoInputConversionMode_bmdVideoInputAnamorphicUpconversion:
    _BMDVideoInputConversionMode = 1634563440;
pub type _BMDVideoInputConversionMode = u32;
pub type BMDVideo3DPackingFormat = u32;
pub const _BMDVideo3DPackingFormat_bmdVideo3DPackingSidebySideHalf: _BMDVideo3DPackingFormat =
    1935831912;
pub const _BMDVideo3DPackingFormat_bmdVideo3DPackingLinebyLine: _BMDVideo3DPackingFormat =
    1818392940;
pub const _BMDVideo3DPackingFormat_bmdVideo3DPackingTopAndBottom: _BMDVideo3DPackingFormat =
    1952539247;
pub const _BMDVideo3DPackingFormat_bmdVideo3DPackingFramePacking: _BMDVideo3DPackingFormat =
    1718775915;
pub const _BMDVideo3DPackingFormat_bmdVideo3DPackingLeftOnly: _BMDVideo3DPackingFormat = 1818584692;
pub const _BMDVideo3DPackingFormat_bmdVideo3DPackingRightOnly: _BMDVideo3DPackingFormat =
    1919510376;
pub type _BMDVideo3DPackingFormat = u32;
pub type BMDIdleVideoOutputOperation = u32;
pub const _BMDIdleVideoOutputOperation_bmdIdleVideoOutputBlack: _BMDIdleVideoOutputOperation =
    1651269987;
pub const _BMDIdleVideoOutputOperation_bmdIdleVideoOutputLastFrame: _BMDIdleVideoOutputOperation =
    1818322529;
pub type _BMDIdleVideoOutputOperation = u32;
pub type BMDVideoEncoderFrameCodingMode = u32;
pub const _BMDVideoEncoderFrameCodingMode_bmdVideoEncoderFrameCodingModeInter:
    _BMDVideoEncoderFrameCodingMode = 1768846437;
pub const _BMDVideoEncoderFrameCodingMode_bmdVideoEncoderFrameCodingModeIntra:
    _BMDVideoEncoderFrameCodingMode = 1768846450;
pub type _BMDVideoEncoderFrameCodingMode = u32;
pub type BMDDNxHRLevel = u32;
pub const _BMDDNxHRLevel_bmdDNxHRLevelSQ: _BMDDNxHRLevel = 1684960113;
pub const _BMDDNxHRLevel_bmdDNxHRLevelLB: _BMDDNxHRLevel = 1684958306;
pub const _BMDDNxHRLevel_bmdDNxHRLevelHQ: _BMDDNxHRLevel = 1684957297;
pub const _BMDDNxHRLevel_bmdDNxHRLevelHQX: _BMDDNxHRLevel = 1684566392;
pub const _BMDDNxHRLevel_bmdDNxHRLevel444: _BMDDNxHRLevel = 1681142836;
pub type _BMDDNxHRLevel = u32;
pub type BMDLinkConfiguration = u32;
pub const _BMDLinkConfiguration_bmdLinkConfigurationSingleLink: _BMDLinkConfiguration = 1818456940;
pub const _BMDLinkConfiguration_bmdLinkConfigurationDualLink: _BMDLinkConfiguration = 1818453100;
pub const _BMDLinkConfiguration_bmdLinkConfigurationQuadLink: _BMDLinkConfiguration = 1818456428;
pub type _BMDLinkConfiguration = u32;
pub type BMDDeviceInterface = u32;
pub const _BMDDeviceInterface_bmdDeviceInterfacePCI: _BMDDeviceInterface = 1885563168;
pub const _BMDDeviceInterface_bmdDeviceInterfaceUSB: _BMDDeviceInterface = 1970496032;
pub const _BMDDeviceInterface_bmdDeviceInterfaceThunderbolt: _BMDDeviceInterface = 1953002862;
pub type _BMDDeviceInterface = u32;
pub type BMDDeckLinkFrameMetadataID = u32;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRElectroOpticalTransferFunc:
    _BMDDeckLinkFrameMetadataID = 1701803110;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelFilmType:
    _BMDDeckLinkFrameMetadataID = 1667658873;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelFilmGauge:
    _BMDDeckLinkFrameMetadataID = 1667655521;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelOffsetDetectedHorizontal:
    _BMDDeckLinkFrameMetadataID = 1868850792;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelOffsetDetectedVertical:
    _BMDDeckLinkFrameMetadataID = 1868850806;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelKeykodeLow:
    _BMDDeckLinkFrameMetadataID = 1667984236;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelKeykodeHigh:
    _BMDDeckLinkFrameMetadataID = 1667984232;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelTile1Size:
    _BMDDeckLinkFrameMetadataID = 1668559219;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelTile2Size:
    _BMDDeckLinkFrameMetadataID = 1668559475;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelTile3Size:
    _BMDDeckLinkFrameMetadataID = 1668559731;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelTile4Size:
    _BMDDeckLinkFrameMetadataID = 1668559987;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelImageWidth:
    _BMDDeckLinkFrameMetadataID = 1230459000;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelImageHeight:
    _BMDDeckLinkFrameMetadataID = 1229475960;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingRedInRed:
    _BMDDeckLinkFrameMetadataID = 1836214642;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingGreenInRed:
    _BMDDeckLinkFrameMetadataID = 1835493746;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingBlueInRed:
    _BMDDeckLinkFrameMetadataID = 1835166066;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingRedInGreen:
    _BMDDeckLinkFrameMetadataID = 1836214631;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingGreenInGreen:
    _BMDDeckLinkFrameMetadataID = 1835493735;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingBlueInGreen:
    _BMDDeckLinkFrameMetadataID = 1835166055;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingRedInBlue:
    _BMDDeckLinkFrameMetadataID = 1836214626;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingGreenInBlue:
    _BMDDeckLinkFrameMetadataID = 1835493730;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLinearMaskingBlueInBlue:
    _BMDDeckLinkFrameMetadataID = 1835166050;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingRedInRed:
    _BMDDeckLinkFrameMetadataID = 1835823730;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingGreenInRed:
    _BMDDeckLinkFrameMetadataID = 1835820914;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingBlueInRed:
    _BMDDeckLinkFrameMetadataID = 1835819634;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingRedInGreen:
    _BMDDeckLinkFrameMetadataID = 1835823719;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingGreenInGreen:
    _BMDDeckLinkFrameMetadataID = 1835820903;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingBlueInGreen:
    _BMDDeckLinkFrameMetadataID = 1835819623;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingRedInBlue:
    _BMDDeckLinkFrameMetadataID = 1835823714;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingGreenInBlue:
    _BMDDeckLinkFrameMetadataID = 1835820898;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLogMaskingBlueInBlue:
    _BMDDeckLinkFrameMetadataID = 1835819618;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelFilmFrameRate:
    _BMDDeckLinkFrameMetadataID = 1667655282;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRDisplayPrimariesRedX:
    _BMDDeckLinkFrameMetadataID = 1751413368;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRDisplayPrimariesRedY:
    _BMDDeckLinkFrameMetadataID = 1751413369;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRDisplayPrimariesGreenX:
    _BMDDeckLinkFrameMetadataID = 1751410552;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRDisplayPrimariesGreenY:
    _BMDDeckLinkFrameMetadataID = 1751410553;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRDisplayPrimariesBlueX:
    _BMDDeckLinkFrameMetadataID = 1751409272;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRDisplayPrimariesBlueY:
    _BMDDeckLinkFrameMetadataID = 1751409273;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRWhitePointX:
    _BMDDeckLinkFrameMetadataID = 1751414648;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRWhitePointY:
    _BMDDeckLinkFrameMetadataID = 1751414649;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRMaxDisplayMasteringLuminance:
    _BMDDeckLinkFrameMetadataID = 1751412076;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRMinDisplayMasteringLuminance:
    _BMDDeckLinkFrameMetadataID = 1752000876;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRMaximumContentLightLevel:
    _BMDDeckLinkFrameMetadataID = 1835232364;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataHDRMaximumFrameAverageLightLevel:
    _BMDDeckLinkFrameMetadataID = 1717660780;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelOffsetToApplyHorizontal:
    _BMDDeckLinkFrameMetadataID = 1869898088;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelOffsetToApplyVertical:
    _BMDDeckLinkFrameMetadataID = 1869898102;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelGainRed:
    _BMDDeckLinkFrameMetadataID = 1281774180;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelGainGreen:
    _BMDDeckLinkFrameMetadataID = 1281771378;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelGainBlue:
    _BMDDeckLinkFrameMetadataID = 1281770092;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLiftRed:
    _BMDDeckLinkFrameMetadataID = 1198412388;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLiftGreen:
    _BMDDeckLinkFrameMetadataID = 1198409586;
pub const _BMDDeckLinkFrameMetadataID_bmdDeckLinkFrameMetadataCintelLiftBlue:
    _BMDDeckLinkFrameMetadataID = 1198408300;
pub type _BMDDeckLinkFrameMetadataID = u32;
pub type BMDDuplexMode = u32;
pub const _BMDDuplexMode_bmdDuplexModeFull: _BMDDuplexMode = 1717859696;
pub const _BMDDuplexMode_bmdDuplexModeHalf: _BMDDuplexMode = 1751414128;
pub type _BMDDuplexMode = u32;
pub type BMDDeckLinkAttributeID = u32;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsInternalKeying: _BMDDeckLinkAttributeID =
    1801812329;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsExternalKeying: _BMDDeckLinkAttributeID =
    1801812325;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsHDKeying: _BMDDeckLinkAttributeID = 1801812328;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsInputFormatDetection: _BMDDeckLinkAttributeID =
    1768842852;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkHasReferenceInput: _BMDDeckLinkAttributeID =
    1752328558;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkHasSerialPort: _BMDDeckLinkAttributeID = 1752395892;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkHasAnalogVideoOutputGain: _BMDDeckLinkAttributeID =
    1635151719;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkCanOnlyAdjustOverallVideoOutputGain:
    _BMDDeckLinkAttributeID = 1870032743;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkHasVideoInputAntiAliasingFilter:
    _BMDDeckLinkAttributeID = 1633773164;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkHasBypass: _BMDDeckLinkAttributeID = 1652125811;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsClockTimingAdjustment:
    _BMDDeckLinkAttributeID = 1668571492;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsFullDuplex: _BMDDeckLinkAttributeID =
    1717859696;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsFullFrameReferenceInputTimingOffset:
    _BMDDeckLinkAttributeID = 1718774126;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsSMPTELevelAOutput: _BMDDeckLinkAttributeID =
    1819700321;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsDualLinkSDI: _BMDDeckLinkAttributeID =
    1935961203;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsQuadLinkSDI: _BMDDeckLinkAttributeID =
    1936813171;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsIdleOutput: _BMDDeckLinkAttributeID =
    1768189813;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkHasLTCTimecodeInput: _BMDDeckLinkAttributeID =
    1751938147;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsDuplexModeConfiguration:
    _BMDDeckLinkAttributeID = 1685418104;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSupportsHDRMetadata: _BMDDeckLinkAttributeID =
    1751413357;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkMaximumAudioChannels: _BMDDeckLinkAttributeID =
    1835098984;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkMaximumAnalogAudioInputChannels:
    _BMDDeckLinkAttributeID = 1767990120;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkMaximumAnalogAudioOutputChannels:
    _BMDDeckLinkAttributeID = 1633772392;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkNumberOfSubDevices: _BMDDeckLinkAttributeID =
    1853055588;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSubDeviceIndex: _BMDDeckLinkAttributeID = 1937072745;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkPersistentID: _BMDDeckLinkAttributeID = 1885694308;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkDeviceGroupID: _BMDDeckLinkAttributeID = 1684498788;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkTopologicalID: _BMDDeckLinkAttributeID = 1953458532;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoOutputConnections: _BMDDeckLinkAttributeID =
    1987011438;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoInputConnections: _BMDDeckLinkAttributeID =
    1986618222;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkAudioOutputConnections: _BMDDeckLinkAttributeID =
    1634689902;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkAudioInputConnections: _BMDDeckLinkAttributeID =
    1634296686;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoIOSupport: _BMDDeckLinkAttributeID = 1986621299;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkDeckControlConnections: _BMDDeckLinkAttributeID =
    1684235118;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkDeviceInterface: _BMDDeckLinkAttributeID = 1684174195;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkAudioInputRCAChannelCount: _BMDDeckLinkAttributeID =
    1634300515;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkAudioInputXLRChannelCount: _BMDDeckLinkAttributeID =
    1634302051;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkAudioOutputRCAChannelCount: _BMDDeckLinkAttributeID =
    1634693731;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkAudioOutputXLRChannelCount: _BMDDeckLinkAttributeID =
    1634695267;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkPairedDevicePersistentID: _BMDDeckLinkAttributeID =
    1886415204;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoInputGainMinimum: _BMDDeckLinkAttributeID =
    1986619245;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoInputGainMaximum: _BMDDeckLinkAttributeID =
    1986619256;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoOutputGainMinimum: _BMDDeckLinkAttributeID =
    1987012461;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVideoOutputGainMaximum: _BMDDeckLinkAttributeID =
    1987012472;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkMicrophoneInputGainMinimum: _BMDDeckLinkAttributeID =
    1835624301;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkMicrophoneInputGainMaximum: _BMDDeckLinkAttributeID =
    1835624312;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkSerialPortDeviceName: _BMDDeckLinkAttributeID =
    1936486510;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkVendorName: _BMDDeckLinkAttributeID = 1986946162;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkDisplayName: _BMDDeckLinkAttributeID = 1685287022;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkModelName: _BMDDeckLinkAttributeID = 1835297902;
pub const _BMDDeckLinkAttributeID_BMDDeckLinkDeviceHandle: _BMDDeckLinkAttributeID = 1684371048;
pub type _BMDDeckLinkAttributeID = u32;
pub type BMDDeckLinkAPIInformationID = u32;
pub const _BMDDeckLinkAPIInformationID_BMDDeckLinkAPIVersion: _BMDDeckLinkAPIInformationID =
    1986359923;
pub type _BMDDeckLinkAPIInformationID = u32;
pub type BMDDeckLinkStatusID = u32;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusDetectedVideoInputMode: _BMDDeckLinkStatusID =
    1685481837;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusDetectedVideoInputFlags: _BMDDeckLinkStatusID =
    1685481830;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusCurrentVideoInputMode: _BMDDeckLinkStatusID =
    1668704621;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusCurrentVideoInputPixelFormat: _BMDDeckLinkStatusID =
    1668704624;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusCurrentVideoInputFlags: _BMDDeckLinkStatusID =
    1668704614;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusCurrentVideoOutputMode: _BMDDeckLinkStatusID =
    1668706157;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusCurrentVideoOutputFlags: _BMDDeckLinkStatusID =
    1668706150;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusPCIExpressLinkWidth: _BMDDeckLinkStatusID =
    1886873956;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusPCIExpressLinkSpeed: _BMDDeckLinkStatusID =
    1886154347;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusLastVideoOutputPixelFormat: _BMDDeckLinkStatusID =
    1869638008;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusReferenceSignalMode: _BMDDeckLinkStatusID =
    1919247981;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusReferenceSignalFlags: _BMDDeckLinkStatusID =
    1919247974;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusDuplexMode: _BMDDeckLinkStatusID = 1685418104;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusBusy: _BMDDeckLinkStatusID = 1651864441;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusInterchangeablePanelType: _BMDDeckLinkStatusID =
    1768124532;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusVideoInputSignalLocked: _BMDDeckLinkStatusID =
    1986622316;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusReferenceSignalLocked: _BMDDeckLinkStatusID =
    1919247980;
pub const _BMDDeckLinkStatusID_bmdDeckLinkStatusReceivedEDID: _BMDDeckLinkStatusID = 1701079396;
pub type _BMDDeckLinkStatusID = u32;
pub type BMDDeckLinkVideoStatusFlags = u32;
pub const _BMDDeckLinkVideoStatusFlags_bmdDeckLinkVideoStatusPsF: _BMDDeckLinkVideoStatusFlags = 1;
pub const _BMDDeckLinkVideoStatusFlags_bmdDeckLinkVideoStatusDualStream3D:
    _BMDDeckLinkVideoStatusFlags = 2;
pub type _BMDDeckLinkVideoStatusFlags = u32;
pub type BMDDuplexStatus = u32;
pub const _BMDDuplexStatus_bmdDuplexStatusFullDuplex: _BMDDuplexStatus = 1717859696;
pub const _BMDDuplexStatus_bmdDuplexStatusHalfDuplex: _BMDDuplexStatus = 1751414128;
pub const _BMDDuplexStatus_bmdDuplexStatusSimplex: _BMDDuplexStatus = 1936747640;
pub const _BMDDuplexStatus_bmdDuplexStatusInactive: _BMDDuplexStatus = 1768841571;
pub type _BMDDuplexStatus = u32;
pub type BMDPanelType = u32;
pub const _BMDPanelType_bmdPanelNotDetected: _BMDPanelType = 1852862060;
pub const _BMDPanelType_bmdPanelTeranexMiniSmartPanel: _BMDPanelType = 1953330029;
pub type _BMDPanelType = u32;
pub type BMDDeviceBusyState = u32;
pub const _BMDDeviceBusyState_bmdDeviceCaptureBusy: _BMDDeviceBusyState = 1;
pub const _BMDDeviceBusyState_bmdDevicePlaybackBusy: _BMDDeviceBusyState = 2;
pub const _BMDDeviceBusyState_bmdDeviceSerialPortBusy: _BMDDeviceBusyState = 4;
pub type _BMDDeviceBusyState = u32;
pub type BMDVideoIOSupport = u32;
pub const _BMDVideoIOSupport_bmdDeviceSupportsCapture: _BMDVideoIOSupport = 1;
pub const _BMDVideoIOSupport_bmdDeviceSupportsPlayback: _BMDVideoIOSupport = 2;
pub type _BMDVideoIOSupport = u32;
pub type BMD3DPreviewFormat = u32;
pub const _BMD3DPreviewFormat_bmd3DPreviewFormatDefault: _BMD3DPreviewFormat = 1684366945;
pub const _BMD3DPreviewFormat_bmd3DPreviewFormatLeftOnly: _BMD3DPreviewFormat = 1818584692;
pub const _BMD3DPreviewFormat_bmd3DPreviewFormatRightOnly: _BMD3DPreviewFormat = 1919510376;
pub const _BMD3DPreviewFormat_bmd3DPreviewFormatSideBySide: _BMD3DPreviewFormat = 1936286821;
pub const _BMD3DPreviewFormat_bmd3DPreviewFormatTopBottom: _BMD3DPreviewFormat = 1953460322;
pub type _BMD3DPreviewFormat = u32;
pub type BMDNotifications = u32;
pub const _BMDNotifications_bmdPreferencesChanged: _BMDNotifications = 1886545254;
pub const _BMDNotifications_bmdStatusChanged: _BMDNotifications = 1937006964;
pub type _BMDNotifications = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_display_mode_iterator {
    _unused: [u8; 0],
}
pub type cdecklink_display_mode_iterator_t = cdecklink_display_mode_iterator;
extern "C" {
    pub fn cdecklink_destroy_display_mode_iterator(it: *mut cdecklink_display_mode_iterator_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_display_mode {
    _unused: [u8; 0],
}
pub type cdecklink_display_mode_t = cdecklink_display_mode;
extern "C" {
    pub fn cdecklink_next_display_mode(
        it: *mut cdecklink_display_mode_iterator_t,
        mode: *mut *mut cdecklink_display_mode_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_destroy_display_mode(mode: *mut cdecklink_display_mode_t);
}
extern "C" {
    pub fn cdecklink_display_mode_name(
        mode: *mut cdecklink_display_mode_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn cdecklink_display_mode_mode(mode: *mut cdecklink_display_mode_t) -> BMDDisplayMode;
}
extern "C" {
    pub fn cdecklink_display_mode_width(
        mode: *mut cdecklink_display_mode_t,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn cdecklink_display_mode_height(
        mode: *mut cdecklink_display_mode_t,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn cdecklink_display_mode_framerate(
        mode: *mut cdecklink_display_mode_t,
        duration: *mut i64,
        scale: *mut i64,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_display_mode_field_dominance(
        mode: *mut cdecklink_display_mode_t,
    ) -> BMDFieldDominance;
}
extern "C" {
    pub fn cdecklink_display_mode_flags(mode: *mut cdecklink_display_mode_t)
        -> BMDDisplayModeFlags;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_video_frame {
    _unused: [u8; 0],
}
pub type cdecklink_video_frame_t = cdecklink_video_frame;
extern "C" {
    pub fn cdecklink_destroy_frame(frame: *mut cdecklink_video_frame_t);
}
extern "C" {
    pub fn cdecklink_video_frame_width(
        frame: *mut cdecklink_video_frame_t,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn cdecklink_video_frame_height(
        frame: *mut cdecklink_video_frame_t,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn cdecklink_video_frame_row_bytes(
        frame: *mut cdecklink_video_frame_t,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn cdecklink_video_frame_pixel_format(
        frame: *mut cdecklink_video_frame_t,
    ) -> BMDPixelFormat;
}
extern "C" {
    pub fn cdecklink_video_frame_flags(frame: *mut cdecklink_video_frame_t) -> BMDFrameFlags;
}
extern "C" {
    pub fn cdecklink_video_frame_bytes(
        frame: *mut cdecklink_video_frame_t,
        buffer: *mut *mut ::std::os::raw::c_void,
    ) -> HRESULT;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_mutable_video_frame {
    _unused: [u8; 0],
}
pub type cdecklink_mutable_video_frame_t = cdecklink_mutable_video_frame;
extern "C" {
    pub fn cdecklink_video_mutable_frame_base(
        frame: *mut cdecklink_mutable_video_frame_t,
    ) -> *mut cdecklink_video_frame_t;
}
extern "C" {
    pub fn cdecklink_destroy_mutable_frame(frame: *mut cdecklink_mutable_video_frame_t);
}
extern "C" {
    pub fn cdecklink_video_mutable_frame_set_flags(
        frame: *mut cdecklink_mutable_video_frame_t,
        newFlags: BMDFrameFlags,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_free_string(str: *const ::std::os::raw::c_char);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_iterator {
    _unused: [u8; 0],
}
pub type cdecklink_iterator_t = cdecklink_iterator;
extern "C" {
    pub fn cdecklink_create_iterator() -> *mut cdecklink_iterator_t;
}
extern "C" {
    pub fn cdecklink_destroy_iterator(it: *mut cdecklink_iterator_t);
}
extern "C" {
    pub fn cdecklink_api_version(it: *mut cdecklink_iterator_t) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_device {
    _unused: [u8; 0],
}
pub type cdecklink_device_t = cdecklink_device;
extern "C" {
    pub fn cdecklink_next_device(
        it: *mut cdecklink_iterator_t,
        device: *mut *mut cdecklink_device_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_destroy_device(device: *mut cdecklink_device_t);
}
extern "C" {
    pub fn cdecklink_device_model_name(
        device: *mut cdecklink_device_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn cdecklink_device_display_name(
        device: *mut cdecklink_device_t,
    ) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cdecklink_device_output {
    _unused: [u8; 0],
}
pub type cdecklink_device_output_t = cdecklink_device_output;
extern "C" {
    pub fn cdecklink_device_output_cast(
        device: *mut cdecklink_device_t,
    ) -> *mut cdecklink_device_output_t;
}
extern "C" {
    pub fn cdecklink_destroy_device_output(output: *mut cdecklink_device_output_t);
}
extern "C" {
    pub fn cdecklink_device_output_does_support_display_mode(
        output: *mut cdecklink_device_output_t,
        displayMode: BMDDisplayMode,
        pixelFormat: BMDPixelFormat,
        flags: BMDVideoOutputFlags,
        result: *mut BMDDisplayModeSupport,
        resultDisplayMode: *mut *mut cdecklink_display_mode_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_display_mode_iterator(
        output: *mut cdecklink_device_output_t,
        iterator: *mut *mut cdecklink_display_mode_iterator_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_enable_video_output(
        output: *mut cdecklink_device_output_t,
        displayMode: BMDDisplayMode,
        flags: BMDVideoOutputFlags,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_disable_video_output(
        output: *mut cdecklink_device_output_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_create_video_frame(
        output: *mut cdecklink_device_output_t,
        width: i32,
        height: i32,
        rowBytes: i32,
        pixelFormat: BMDPixelFormat,
        flags: BMDFrameFlags,
        outFrame: *mut *mut cdecklink_mutable_video_frame_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_display_video_frame_sync(
        output: *mut cdecklink_device_output_t,
        frame: *mut cdecklink_video_frame_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_schedule_video_frame(
        output: *mut cdecklink_device_output_t,
        theFrame: *mut cdecklink_video_frame_t,
        displayTime: i64,
        displayDuration: i64,
        timeScale: i64,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_buffered_video_frame_count(
        output: *mut cdecklink_device_output_t,
        bufferedFrameCount: *mut u32,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_enable_audio_output(
        output: *mut cdecklink_device_output_t,
        sampleRate: BMDAudioSampleRate,
        sampleType: BMDAudioSampleType,
        channelCount: u32,
        streamType: BMDAudioOutputStreamType,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_disable_audio_output(
        output: *mut cdecklink_device_output_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_write_audio_samples_sync(
        output: *mut cdecklink_device_output_t,
        buffer: *mut ::std::os::raw::c_void,
        sampleFrameCount: u32,
        sampleFramesWritten: *mut u32,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_begin_audio_preroll(
        output: *mut cdecklink_device_output_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_end_audio_preroll(
        output: *mut cdecklink_device_output_t,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_schedule_audio_samples(
        output: *mut cdecklink_device_output_t,
        buffer: *mut ::std::os::raw::c_void,
        sampleFrameCount: u32,
        streamTime: i64,
        timeScale: i64,
        sampleFramesWritten: *mut u32,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_buffered_audio_sample_frame_count(
        output: *mut cdecklink_device_output_t,
        bufferedSampleFrameCount: *mut u32,
    ) -> HRESULT;
}
extern "C" {
    pub fn cdecklink_device_output_flush_buffered_audio_samples(
        output: *mut cdecklink_device_output_t,
    ) -> HRESULT;
}
